# Use an official Python runtime as a parent image
FROM python:3.9

# Set the working directory in the container
WORKDIR /key_server

# Copy the current directory contents into the container at /key_server
COPY . .

# Install any needed dependencies specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Make port 5050 available to the world outside this container
EXPOSE 5050
